# SPDX-FileCopyrightText: 2025 Jankari Tech Pvt. Ltd.
# SPDX-License-Identifier: AGPL-3.0-or-later
services:
  keycloak-db:
    image: postgres:14
    restart: unless-stopped
    networks:
      - nc-op
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
      PGUSER: keycloak
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready', '-d', 'db_prod']
      interval: 10s
      timeout: 30s
      retries: 5
      start_period: 10s

  keycloak:
    image: quay.io/keycloak/keycloak:26.2
    restart: unless-stopped
    command:
      [
        'start-dev',
        '--proxy-headers',
        'xforwarded',
        '--spi-connections-http-client-default-disable-trust-manager=true',
        '--import-realm'
      ]
    environment:
      KC_DB: postgres
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak
      KC_DB_URL: jdbc:postgresql://keycloak-db:5432/keycloak
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      KC_DB_SCHEMA: public
      KC_HOSTNAME: keycloak.local
      KC_FEATURES: preview
      KC_TRANSACTION_XA_ENABLED: false
    networks:
      - nc-op
    volumes:
      - ./opnc-realm.json:/opt/keycloak/data/import/opnc-realm.json
      - step:/step:ro
      - keycloakdata:/opt/keycloak/data/
    labels:
      traefik.enable: true
      traefik.http.routers.keycloak.rule: Host(`keycloak.local`)
      traefik.http.routers.keycloak.entrypoints: websecure
    depends_on:
      traefik:
        condition: service_started
      keycloak-db:
        condition: service_healthy

volumes:
  keycloakdata:
