# SPDX-FileCopyrightText: 2023-2025 Jankari Tech Pvt. Ltd.
# SPDX-License-Identifier: AGPL-3.0-or-later
name: Nightly CI (Release branch)

# workflow can be scheduled ONLY from DEFAULT branch
# > This event will only trigger a workflow run if the workflow file is on the default branch.
# See: https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows#schedule
on: [ pull_request ]

jobs:
  builds:
    uses: ./.github/workflows/shared_workflow.yml
    secrets: inherit
    with:
      branch: release/2.11

  upgrade-test:
    uses: ./.github/workflows/app-upgrade.yml
    with:
      branch: release/2.11

  notify-nightly-report:
    needs: [builds, upgrade-test]
    if: ${{ always() }}
    runs-on: ubuntu-22.04
    steps:
      - name: checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8
      
      - name: Notify Element (nightly builds)
        # env:
        #   ELEMENT_CHAT_URL: ${{ secrets.ELEMENT_CHAT_URL }}
        #   ELEMENT_ROOM_ID: ${{ secrets.ELEMENT_ROOM_ID }}
        #   NIGHTLY_CI_USER_TOKEN: ${{ secrets.NIGHTLY_CI_USER_TOKEN }}
        #   GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        #   REPO_OWNER: nextcloud
        #   REPO_NAME: integration_openproject
        #   RUN_ID: ${{ github.run_id }}
        #   BRANCH_NAME: ${{ inputs.branch }}
        #   WORKFLOW_STATUS: ${{ needs.builds.result }}
        #   JOB_NAME: builds
        run: |
          echo '${{ toJson(needs) }}'
          

      # - name: Notify Element (upgrade tests)
      #   env:
      #     ELEMENT_CHAT_URL: ${{ secrets.ELEMENT_CHAT_URL }}
      #     ELEMENT_ROOM_ID: ${{ secrets.ELEMENT_ROOM_ID }}
      #     NIGHTLY_CI_USER_TOKEN: ${{ secrets.NIGHTLY_CI_USER_TOKEN }}
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #     REPO_OWNER: nextcloud
      #     REPO_NAME: integration_openproject
      #     RUN_ID: ${{ github.run_id }}
      #     BRANCH_NAME: ${{ inputs.branch }}
      #     WORKFLOW_STATUS: ${{ needs.upgrade-test.result }}
      #     JOB_NAME: upgrade-test
      #   run: ./.github/scripts/notify-to-element.sh