# SPDX-FileCopyrightText: 2026 Jankari Tech Pvt. Ltd.
# SPDX-License-Identifier: AGPL-3.0-or-later

name: Upgrade Testing

on: [pull_request]

jobs:
  create-matrix:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8

      - name: Create matrix
        id: create-matrix
        env:
          NEXTCLOUD_VERSIONS: "29 30"
          PHP_VERSIONS: "8.2 8.3"
        run: |
          MATRIX=$(./.github/scripts/generate-matrix.sh)
          echo "matrix={\"include\": [$MATRIX]}" >> $GITHUB_OUTPUT
    outputs:
      matrix: ${{ steps.create-matrix.outputs.matrix }}

  upgrade-test:
    name: Upgrade Testing
    needs: create-matrix
    if: ${{ success() }}
    strategy:
      matrix: ${{ fromJson(needs.create-matrix.outputs.matrix) }}
    runs-on: ubuntu-latest

    env:
      DJANGO_SETTINGS_MODULE: nextcloudappstore.settings.development
      PREVIOUS_APP_VERSION: 2.9.2
      UPGRADE_APP_VERSION: 2.10.0
      APPSTORE_BASE_URL: http://localhost:8000
    services:
      database-mysql:
        image: ghcr.io/nextcloud/continuous-integration-mariadb-10.5:latest
        env:
          MYSQL_ROOT_PASSWORD: 'nextcloud'
          MYSQL_PASSWORD: 'nextcloud'
          MYSQL_USER: 'nextcloud'
          MYSQL_DATABASE: 'nextcloud'
        ports:
          - 3306:3306

    steps:
      - name: Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8
        with:
          path: integration_openproject
          fetch-tags: true
          ref: v${{ env.UPGRADE_APP_VERSION }}

      - name: Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8
        with:
          repository: nextcloud/activity
          ref: ${{ matrix.nextcloudVersion }}
          path: activity
          
      - name: Setup NodeJS
        uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238
        with:
          node-version: 20

      - name: Setup npm
        run: npm i -g npm

      - name: Setup PHP
        uses: shivammathur/setup-php@a4e22b60bbb9c1021113f2860347b0759f66fe5d
        with:
          php-version: ${{ format('{0}.{1}', matrix.phpVersionMajor,matrix.phpVersionMinor) }}
          extensions: mbstring, intl, mysql, gd
          ini-values: post_max_size=256M, max_execution_time=180

      - name: Build nextcloud project
        run: |
          export DEBIAN_FRONTEND=noninteractive
          echo "###### installing nextcloud"
          mkdir ~/html
          git clone https://github.com/nextcloud/server.git --recursive --depth 1 -b ${{ matrix.nextcloudVersion }} ~/html/nextcloud
          cd ~/html/nextcloud
          git submodule update --init
          mkdir -p data
          php occ maintenance:install \
            --database mysql \
            --database-name nextcloud \
            --database-host 127.0.0.1 \
            --database-user nextcloud \
            --database-pass nextcloud \
            --admin-user admin \
            --admin-pass admin
          php occ maintenance:mode --off
          sudo php -S localhost:80 -t ~/html/nextcloud &

      - name: Wait for Nextcloud server to be ready
        run: |
          if ! timeout 5m bash -c '
            until curl -s -f http://localhost/status.php | grep '"'"'"installed":true'"'"'; do
              echo "[INFO] Waiting for server to be ready..."
              sleep 10
            done
          '; then
            echo "[ERROR] Server not ready within 5 minutes."
            exit 1
          fi


      - name: Setup System dependencies for appstore
        run: |
          sudo apt install -y \
            python3-venv \
            python3-wheel \
            libxslt-dev \
            libxml2-dev \
            libz-dev \
            libpq-dev \
            build-essential \
            python3-dev \
            python3-setuptools \
            gettext \
            libssl-dev \
            libffi-dev \
            nodejs \
            yarn
        
      - name: Checkout appstore
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8
        with:
          repository: nextcloud/appstore
          path: appstore

      - name: Install Appstore
        run: |
          cd appstore
          python3 -m venv venv
          source venv/bin/activate
          pip install poetry==1.8.2
          make dev-setup
          python manage.py runserver &
      
      - name: Check for Appstore
        run: |
          cd appstore
          status=$(curl -o /dev/null -s -w "%{http_code}" "$APPSTORE_BASE_URL")
          if [ "$status" -eq 200 ]; then
            echo "OK"
          else
            echo "FAILED (status: $status)"
          fi
        
      - name: Register and publish integration_openproject apps
        env:
          APP_VERSION: ${{ env.PREVIOUS_APP_VERSION }}
        run: |
          wget https://raw.githubusercontent.com/nextcloud/integration_openproject/${{github.head_ref}}/.github/scripts/register-and-publish-app-to-self-hosted-appstore.sh
          bash ./register-and-publish-app-to-self-hosted-appstore.sh

      - name: Enable other apps from official app store
        run: |
          cp -R activity ~/html/nextcloud/apps
          cd ~/html/nextcloud
          php occ app:enable oidc user_oidc groupfolders activity

      - name: Enable integration_openproject app from self-hosted app store
        run: |
          # making the signature verification always pass for testing
          # by making the $verified variable true in Installer.php
          sed -i.bak 's/$verified = .*/$verified = true;/' /home/runner/html/nextcloud/lib/private/Installer.php || {
          echo "::error::Failed to patch Installer.php with sed"
          exit 1
          }
          # latest data didn't get fetched properly, so we need to clear the appstore cache
          echo "" > ~/html/nextcloud/data/appdata_*/appstore/apps.json
          cd ~/html/nextcloud
          php occ config:system:set ratelimit.protection.enabled --value false --type bool
          php occ config:system:set appstoreurl --value "$APPSTORE_BASE_URL/api/v1"
          php occ config:system:set allow_local_remote_servers --value true
          php occ app:install integration_openproject

      - name: Register and publish next release of the app
        env:
          APP_VERSION: ${{ env.UPGRADE_APP_VERSION }}
        run: |
          bash ./register-and-publish-app-to-self-hosted-appstore.sh

      - name: upgrade apps
        run: |
          cd ~/html/nextcloud
          # latest data didn't get fetched properly, so we need to clear the appstore cache
          echo "" > ~/html/nextcloud/data/appdata_*/appstore/apps.json
          php occ app:update --allow-unstable integration_openproject

      - name: API Tests
        env:
          NEXTCLOUD_BASE_URL: http://localhost
        run: |
          cd integration_openproject
          # build apps
          make
          # Run API tests
          make api-test