# SPDX-FileCopyrightText: 2023 Jankari Tech Pvt. Ltd.
# SPDX-License-Identifier: AGPL-3.0-or-later
name: CI

on:
  push:
    branches:
      - 'master'
  pull_request:
    paths-ignore:
      - '**.md'
      - '**.txt'
      - '**.sh'
      - 'dev/**'
      - 'l10n/**'
      - 'img/**'
      - 'docker-compose*'

jobs:
  builds:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
        - name: Checkout server (for phpunit and psalm)
          uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8
          with:
            submodules: true
            repository: nextcloud/server
            path: server
            ref: stable33

        - name: path checking
          run: |
            pwd
            ls -l
            cd integration_openproject
            ls -l

        - name: path check
          run: |
            git clone https://github.com/nextcloud/integration_openproject.git
            cd integration_openproject
            git checkout release/3.0
            git branch
            git pull